name: madrasty
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  age: ^0.0.1
  provider: ^4.3.2+3
  fancy_on_boarding: ^1.7.0
  intl: ^0.16.1
  flutter_countdown_timer: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/classwork.png
    - assets/icons/timer.png
    - assets/icons/attendence.png
    - assets/icons/evulation.png
    - assets/icons/exams.png
    - assets/icons/balance.png
    - assets/icons/extraclasses.png
    - assets/icons/homework.png
    - assets/icons/library.png
    - assets/icons/book.png
    - assets/icons/money.png
    - assets/icons/projects.png
    - assets/icons/schedule.png
    - assets/icons/announcment.png
    - assets/icons/transport.png
    - assets/icons/stuff.png
    - assets/icons/survey.png
    - assets/icons/students.png
    - assets/icons/activity.png
    - assets/icons/math.png
    - assets/icons/arab.png
    - assets/icons/lang.png
    - assets/icons/science.png
    - assets/icons/art.png
    - assets/icons/social.png
    - assets/icons/religion.png
    - assets/icons/notf.png
    - assets/icons/teachers.png
    - assets/icons/busuper.png
    - assets/icons/admins.png
    - assets/icons/guards.png
    - assets/icons/leaders.png
    - assets/icons/classes.png
    - assets/icons/1.png
    - assets/icons/2.png
    - assets/icons/3.png
    - assets/icons/4.png
    - assets/icons/5.png
    - assets/svgs/slide1.svg
    - assets/svgs/slide2.svg
    - assets/svgs/slide3.svg
    - assets/svgs/slide4.svg
    - assets/slides/slide1.png
    - assets/slides/slide2.png
    - assets/slides/slide3.png
    - assets/slides/slide4.png
    - assets/avatars/hulk.jpg
    - assets/avatars/canary.jpg
    - assets/avatars/dare.jpg
    - assets/avatars/green.jpg
    - assets/avatars/spiderman.png
    - assets/avatars/superman.jpg
    - assets/avatars/thor.jpg
    - assets/avatars/capten.jpg
    - assets/avatars/zod.jpg
    - assets/avatars/blackwidow.jpg
    - assets/avatars/antwoman.jpg
    - assets/avatars/antman.png
    - assets/avatars/aly.jpeg
    - assets/illustrations/nomail.png
    - assets/illustrations/illus2.png
    - assets/illustrations/leavereq.png
    - assets/illustrations/emaxSubmited.png
    - assets/illustrations/notfi.png
    - assets/illustrations/check_mail.png
    - assets/images/class1.png
    - assets/images/class2.png
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Black.ttf
           weight: 900
         - asset: assets/fonts/Montserrat-BlackItalic.ttf
           weight: 900
           style: italic
         - asset: assets/fonts/Montserrat-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: assets/fonts/Montserrat-Bold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/fonts/Montserrat-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: assets/fonts/Montserrat-Medium.ttf
           weight: 500
         - asset: assets/fonts/Montserrat-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Montserrat-Regular.ttf
           weight: 400
         - asset: assets/fonts/Montserrat-Light.ttf
           weight: 300
         - asset: assets/fonts/Montserrat-LightItalic.ttf
           weight: 300
           style: italic
         - asset: assets/fonts/Montserrat-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
           weight: 200
           style: italic
         - asset: assets/fonts/Montserrat-Thin.ttf
           weight: 100
         - asset: assets/fonts/Montserrat-ThinItalic.ttf
           weight: 100
           style: italic
      
           
          
      
     - family: MyFlutterApp
       fonts:
         - asset: assets/fonts/MyFlutterApp.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
